name: publish

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
          - uses: actions/checkout@v2
          - name: Login to GitHub Container Registry  
            uses: docker/login-action@v1
            with:
                     registry: ghcr.io
                     username: ${{ github.actor }}   
                     password: ${{ secrets.GITHUB_TOKEN }}
       
          - name: Build the hello-docker Docker image 
            run: |
              docker build -t ubuntu_24_dqrobotics ubuntu_24/dqrobotics
              docker push juanjqo/docker_images/ubuntu_24_dqrobotics
       

