name: publish

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
          - uses: actions/checkout@v2
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
             username: ${{ vars.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3    
       
          - name: Build and push ubuntu_24_dqrobotics
            uses: docker/build-push-action@v6
            with:
              # platforms: linux/amd64,linux/arm64
              platforms: linux/amd64
              push: true
              file: ubuntu_24/dqrobotics/Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/ubuntu_24_dqrobotics

          - name: Build and push ubuntu_24_dqrobotics_ros_jazzy 
            uses: docker/build-push-action@v6
            with:
              # platforms: linux/amd64,linux/arm64
              platforms: linux/amd64
              push: true
              file: ubuntu_24/dqrobotics_ros_jazzy/Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/ubuntu_24_dqrobotics_ros_jazzy
              
          - name: Build and push sas_robot_driver_unitree_b1z1
            uses: docker/build-push-action@v6
            with:
              # platforms: linux/amd64,linux/arm64
              platforms: linux/amd64
              push: true
              file: ubuntu_24/sas_robot_driver_unitree_b1z1/Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/sas_robot_driver_unitree_b1z1             
           

